version: '3'
services:
  app:
    container_name: auth_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
      - '9229:9229'
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
